### ISSUE TITLE
Wiki / Installer Doesn't Demand Python3

### ISSUE THREAD

**Issue by mikeperalta1** [armadillica/pillar#3] opened 2017-10-30 04:11 UTC
Hey all,

Per the wiki on this repo, I attempted to run the command:
`pip install -e ../pillar.git`
While inside my pillar clone at /home/pillar/Documents/pillar.git

The installer failed with the following message:

>     Complete output from command /usr/bin/python2 -c "import setuptools, tokenize;__file__='/home/pillar/Documents/pillar.git/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps --user --prefix=:
>     running develop
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/home/pillar/Documents/pillar.git/setup.py", line 70, in <module>
>         zip_safe=False,
>       File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
>         dist.run_commands()
>       File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/home/pillar/Documents/pillar.git/setup.py", line 20, in run
>         super().run()
>     TypeError: super() takes at least 1 argument (0 given)

I'm not sure, but I believe this is due to my "pip" command being linked to Python2. When I then ran the same command, only using "pip3", I made it past this error.

It's just that the Wiki doesn't specify Python3, and the installer doesn't seem to enforce a Python version.

I'm using Fedora 26, Python 2.7.13, and "pip 9.0.1 from /usr/lib/python2.7/site-packages (python 2.7)"

I apologize in advance if this is an ignorant submission. I'm not familiar with this at all yet, and have barely started to learn Python myself. Hopefully this is helpful.

**Comment by dfelinto** [comment] 2017-10-30 11:39
For the records, the official installation guide does mention Python 3:
https://pillarframework.org/development/install/

So maybe the issue is not referring to this guide in the README?

**Comment by mikeperalta1** [comment] 2017-10-30 13:44
Perhaps yeah. A link to the official install guide would have helped probably. I'll go read it now. Thanks for the link!

**Comment by sybrenstuvel** [comment] 2018-04-27 08:41
Please assume that everything is for the current version of Python 3 unless explicitly mentioning it's compatible with Python 2.

**Comment by venomgfx** [comment] 2019-07-08 08:59
Closing this issue:

* Python 3.6 is mentioned in the guide
* Pillar now uses Poetry for dependencies
* It's been a while

**Closed as completed by venomgfx** 2019-07-08 08:59 UTC
